
STATUS_HEIGHT = 1

LOG_HINT_ENVVAR = "MUXEC_LOG"
LOG_FILE_PATH = "/tmp/muxec.log"
DEBUG_HINT_ENVVAR = "MUXEC_DEBUG"

MODE_TTY = "tty"
MODE_PLAIN = "plain"
MODE_AUTO = "auto"

BACKSPACE_ORD = 8
ESCAPE_ORD = 27
LF_ORD = 10
CR_ORD = 13
CSI_PREFIX = '['
CSI_PARAM_SEPARATOR = ';'
CSI_CURSOR_UP = 'A'
CSI_CURSOR_DOWN = 'B'
CSI_CURSOR_FORWARD = 'C'
CSI_CURSOR_BACK = 'D'
CSI_CURSOR_POSITION = 'H'
CSI_CURSOR_ERASE_IN_LINE = 'K'
CSI_CURSOR_ERASE_IN_DISPLAY = 'J'
