name: publish
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  - name: Publish to pypi
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      user: ReallyLiri
      password: ${{ secrets.PYPI }}
